name: magnojet
description: Aplicativo MagnoJet para seleção de pontas de pulverização agrícola.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI e Design
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8

  # Utilitários
  path: ^1.9.1
  logger: ^2.6.2
  intl: ^0.20.2
  shared_preferences: ^2.5.4

  # Para download e abertura de arquivos
  permission_handler: ^11.4.0
  open_file: ^3.5.11
  http: ^1.6.0
  device_info_plus: ^12.3.0
  flutter_media_store: ^1.3.1

  # Para Compartilhamento
  share_plus: ^12.0.1

  # Armazenamento Local
  sqflite: ^2.4.2
  path_provider: ^2.1.5

  # Localização e GPS
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Notificações Push
  timezone: ^0.9.2
  flutter_timezone: ^3.0.1
  uuid: ^4.3.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^17.1.2

  # Mídia
  image_picker: ^1.2.1

  # Conectividade
  connectivity_plus: ^7.0.0

  # Backend e Autenticação
  supabase_flutter: ^2.12.0

  # Variáveis de Ambiente
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de Ícones
  flutter_launcher_icons: ^0.14.4

  # Qualidade de Código
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "assets/icon_normal.png"
  ios: true
  android: true
  adaptive_icon_background: "#15325a"
  adaptive_icon_foreground: "assets/icon_normal.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/icon_normal.png
    - assets/icon_monochromatic.png
    - assets/logo_branca.png
