name: magnojet
description: Aplicativo MagnoJet para seleção de pontas de pulverização agrícola.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI e Design
  material_design_icons_flutter: ^7.0.7296
  cupertino_icons: ^1.0.8

  # Utilitários
  path: ^1.9.1
  logger: ^2.3.0
  intl: ^0.20.2
  shared_preferences: ^2.2.2

  # Armazenamento Local
  sqflite: ^2.3.3
  path_provider: ^2.1.3

  # Localização e GPS
  geolocator: ^11.0.0
  geocoding: ^2.1.0

  # Mídia
  image_picker: ^1.0.4

  # Conectividade
  connectivity_plus: ^7.0.0

  # Backend e Autenticação
  supabase_flutter: ^2.10.3

  # Variáveis de Ambiente
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de Ícones
  flutter_launcher_icons: ^0.14.4

  # Qualidade de Código
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  image_path: "assets/icon_normal.png"
  ios: true
  android: true
  adaptive_icon_background: "#15325a"
  adaptive_icon_foreground: "assets/icon_normal.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png
    - assets/icon_normal.png
    - assets/icon_monochromatic.png
    - assets/logo_branca.png
